# PCA Homework
### Micael Fernandes - 201906840029

### 1)	
Quais as duas componentes principais? Quais os autovalores e as variâncias associadas com estas duas componentes principais?


In [ ]:
'''
Dados:
X=
[ 1 0
  2 0
  3 0
  5 6
  6 6
  7 6 ]
'''


<img alt="geo1" src="./imgs/geo1.png">
<img alt="geo5"src="./imgs/geo5.jpg">
<img alt="geo2" src="./imgs/geo2.png">
<img alt="geo3" src="./imgs/geo3.jpg">



### 2)	
Considere que realizamos uma PCA em um conjunto de dados bidimensional e obtemos os autovalores 6 e 2. Desenhe uma distribuição de pontos amostrais que podem dar origem a este resultado. Além disso, desenhe os dois autovetores.

<img alt="sol1" src="./imgs/sol1.jpg">
<img alt="geo6" src="./imgs/geo6.png">

### 3)	
Considere 3 pontos de dados em um espaço bidimensional R**2: (-1, 1), (0, 0), (1, 1). Qual é o primeiro componente principal do conjunto de dados fornecido?

<img alt="geo7" src="./imgs/geo7.jpg">

In [38]:
import numpy as np

d = np.array([[-1, 1], [0, 0], [1, 1]])
my_pca = PCA(2)
my_pca.fit_transform(d)
print("Autovetores: \n", my_pca.eigenvectors)
print("Autovalores: \n",my_pca.eigenvalues)


[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Autovetores: 
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
Autovalores: 
 [1. 1.]


### 4)	
Suponha que realizamos PCA em um conjunto de dados bidimensional e o resultado são dois autovalores iguais. O que isso significa em relação à importância de cada dimensão? Buscar uma redução de dimensionalidade seria uma boa escolha neste caso? Por favor explique. Esboce um conjunto de dados em que seus dois autovalores tenham o mesmo tamanho.

<b>Solução: </b></br>
Os valores teram igual variancia de componentes principais. Assim não tera muita variabilidade e a "importancia" dos dados para aquele treinamento será a mesma. Ou seja, cada dimensão terá a mesma importacia e impactara no aprendizado. Logo, buscando a maxima exploração dos dados para o modelo não perder informação, não é muito viavel a reduzir a dimensionalidade nesse caso, uma vez que a variabilidade dos PCAs é a mesma.

### 5)	
Explique o motivo de uso de SVD na PCA do scikit-learn.

<img alt="svd" src="./imgs/svd.jpg">

### 6)
Acompanhe o tutorial em [2] e implemente o código em Python que realiza a PCA em um dataset com mais de 3 parâmetros de entrada (“features”), de forma a converter este dataset em um novo dataset com apenas duas “features”.

In [70]:
import numpy as np

class PCA:
    def __init__(self, n_components=2) -> None:
        self.n_components = n_components

    def fit_transform(self, X):
        # get number of samples and components
        self.n_samples = X.shape[0]

        # standardize data
        self.A = self.standardize_data(X)
        # calculate covariance matrix
        self.covariance_matrix = self.get_covariance_matrix()
        # retrieve selected eigenvectors
        self.eigenvectors = self.get_eigenvectors(self.covariance_matrix)
        # project into lower dimension
        self.projected_matrix = self.project_matrix(self.eigenvectors)
        return self.projected_matrix

    def standardize_data(self, X):
        # subtract mean and divide by standard deviation columnwise
        numerator = X - np.mean(X, axis=0)
        denominator = np.std(X, axis=0)
        return numerator / denominator

    def get_covariance_matrix(self, ddof=0):
        # calculate covariance matrix with standardized matrix A
        C = np.dot(self.A.T, self.A) / (self.n_samples - ddof)
        return C

    def get_eigenvectors(self, C):
        # calculate eigenvalues & eigenvectors of covariance matrix 'C'
        self.eigenvalues, eigenvectors = np.linalg.eig(C)
        
        # sort eigenvalues descending and select columns based on n_components
        n_cols = np.argsort(self.eigenvalues)[::-1][: self.n_components]
        selected_vectors = eigenvectors[:, n_cols]
        return selected_vectors

    def project_matrix(self, eigenvectors):
        P = np.dot(self.A, eigenvectors)
        return P


d = np.array([
    [-1, .5**.5, 3], 
    [-1, 0, -2], 
    [-1, -(.5**.5), 5], 
    [1, 0, 9], 
    [1, .5**.5, 2.7], 
    [1, -(.5**.5), 0]])
    
my_pca = PCA(2)
my_pca.fit_transform(d)
print("Eigenvectors: \n", my_pca.eigenvectors)
print("Eigenvalues: \n",my_pca.eigenvalues)
print("PCA 1: ", (my_pca.eigenvalues[1]/my_pca.eigenvalues.sum())*100)
print("PCA 2: ", (my_pca.eigenvalues[2]/my_pca.eigenvalues.sum())*100)
print("PCA 3: ", (my_pca.eigenvalues[0]/my_pca.eigenvalues.sum())*100)
print("Final Matrix: \n",my_pca.projected_matrix)


Eigenvectors: 
 [[-6.99241769e-01  1.48734314e-01]
 [-1.05171042e-01 -9.88877194e-01]
 [-7.07106781e-01  1.35632157e-18]]
Eigenvalues: 
 [0.72658582 1.27341418 1.        ]
PCA 1:  42.44713943900227
PCA 2:  33.33333333333333
PCA 3:  24.219527227664408
Final Matrix: 
 [[ 0.56037183 -1.35985659]
 [ 1.69540383 -0.14873431]
 [ 0.4154975   1.06238796]
 [-1.91677317  0.14873431]
 [-0.77773825 -1.06238796]
 [ 0.02323826  1.35985659]]
